main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from main import views, forms


urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('create_project/', views.create_project, name='create_project'),
    path('sign-up/', views.SignUpView.as_view(), name='signup'),
    path('sign-in/', auth_views.LoginView.as_view(template_name='sign-in.html', form_class=forms.AuthenticationForm), name='sign-in'),
    path('sign-out/', views.sign_out, name='sign-out'),
    path('confirm_email/', views.EmailConfirmationView.as_view(), name='confirm_email'),
    path('upload/', views.FileUploadView.as_view(), name='upload'),
]

smallrna/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/forms.py
import datetime

from django import forms
from django.core.mail import send_mail
from django.contrib.auth.forms import UserCreationForm as DjangoUserCreationForm
from django.contrib.auth.forms import UsernameField
from django.contrib.auth import authenticate
from . import models
import logging
from random import randint

logger = logging.getLogger(__name__)


class CreateProjectForm(forms.Form):
    create_project_name = forms.CharField(min_length=3, max_length=128)
    create_project_description = forms.CharField(min_length=3)


class EmailConfirmationForm(forms.Form):
    email_code = forms.CharField(min_length=6, max_length=6)

    def update_model(self, confirmation):
        print('update_model')
        confirmation.confirmed_on = datetime.datetime.now()
        confirmation.user.can_ask = True
        confirmation.user.email_confirmed = True
        confirmation.user.save()
        confirmation.status = True
        confirmation.save()


class AuthenticationForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(strip=False, widget=forms.PasswordInput)

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user = None
        super().__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        if email is not None and password:
            self.user = authenticate(self.request, email=email, password=password)
            if self.user is None:
                raise forms.ValidationError('Invalid e-mail or password.')
            logger.info(f'{self.user} is logged in')
        return self.cleaned_data

    def get_user(self):
        return self.user


class UserCreationForm(DjangoUserCreationForm):
    class Meta(DjangoUserCreationForm.Meta):
        model = models.User
        fields = ('email',)
        field_classes = {'email':UsernameField}

    def create_email_confirmation_code(self, user):
        random_code = randint(111111, 999999)
        confirmation = models.EmailConfirmation(user=user, sent_key=random_code)
        confirmation.save()
        return random_code

    def send_mail(self, code):
        logger.info('sending sign-up email for %s', self.cleaned_data['email'])

        message = 'Welcome {}! Please enter the following code to confirm your e-mail address: {} '.format(self.cleaned_data['email'], code)
        send_mail('Welcome to smallRNA!', message, 'welcome@smallrna.com',
                  [self.cleaned_data['email']], fail_silently=True)

templates/_modal_add_dataset.html
<div class="modal fade" id="addDatasetModal" tabindex="-1" role="dialog" aria-labelledby="Add Dataset to the Project" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addDatasetTitle">Add Dataset to the Project</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div onclick="openNewDatasetModal()" class="jumbotron col-md-6 bg-white text-center jumbotron-link text-black-50">
            <h1 class="display-5">Create New Dataset</h1>
            <p class="lead">Upload FASTQ files</p>
          </div>
          <div onclick="openChooseDatasetModal()" class="jumbotron col-md-6 bg-white text-center jumbotron-link text-black-50">
            <h1 class="display-5">Choose Existing Dataset</h1>
            <p class="lead">Use already uploaded data</p>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<script>
  function openNewDatasetModal() {
      $('#addDatasetModal').modal('hide')
      $('#newDatasetModal').modal('show')
  }

  function openChooseDatasetModal() {
      $('#addDatasetModal').modal('hide')
      $('#chooseDatasetModal').modal('show')
  }
</script>

templates/_modal_choose_dataset.html
<div class="modal fade" id="addDatasetModal" tabindex="-1" role="dialog" aria-labelledby="Add Dataset to the Project" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addDatasetTitle">Add Dataset to the Project</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div onclick="openNewDatasetModal()" class="jumbotron col-md-6 bg-white text-center jumbotron-link text-black-50">
            <h1 class="display-5">Create New Dataset</h1>
            <p class="lead">Upload FASTQ files</p>
          </div>
          <div onclick="openChooseDatasetModal()" class="jumbotron col-md-6 bg-white text-center jumbotron-link text-black-50">
            <h1 class="display-5">Choose Existing Dataset</h1>
            <p class="lead">Use already uploaded data</p>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<script>
  function openNewDatasetModal() {
      $('#addDatasetModal').modal('hide')
      $('#newDatasetModal').modal('show')
  }

  function openChooseDatasetModal() {
      $('#addDatasetModal').modal('hide')
      $('#chooseDatasetModal').modal('show')
  }
</script>

templates/_modal_create_project.html
<div class="modal fade" id="createNewProjectModal" tabindex="-1" role="dialog" aria-labelledby="Create New Project" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="createNewProjectTitle">Create New Project</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="/create_project/" method="post">
        {% csrf_token %}
        <div class="modal-body">
        <div class="col-md-12">
          <div class="form-group mt-3">
            <input type="text" name="create_project_name" id="create_project_name" class="form-control" required autofocus maxlength="128">
            <label class="form-control-placeholder" for="create_project_name">Project Name</label>
          </div>
          <div class="form-group mt-4">
            <textarea name="create_project_description" id="create_project_description" class="form-control" rows="3" required></textarea>
            <label class="form-control-placeholder" for="create_project_description">Description</label>
          </div>
        </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" role="button" class="btn btn-primary">Create!</button>
        </div>
      </form>
    </div>
  </div>
</div>

templates/_modal_new_project.html
<div class="modal fade" tabindex="-1" role="dialog" id="createNewProject">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Create New Project</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Modal body text goes here.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary">Create Project!</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static "css/floating_label.css" %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/solid.css" integrity="sha384-ioUrHig76ITq4aEJ67dHzTvqjsAP/7IzgwE7lgJcg2r7BRNGYSK0LwSmROzYtgzs" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/fontawesome.css" integrity="sha384-sri+NftO+0hcisDKgr287Y/1LVnInHJ1l+XC7+FOabmTTIK0HnE2ID+xxvJ21c5J" crossorigin="anonymous">
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="https://d3js.org/d3.v5.min.js"></script>
    <title>Data Preprocessing</title>
</head>
<body class="bg-light">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a class="navbar-brand" href="/">Mello Lab</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.path == "/ask/" %}active {% endif %}"">
                    <a class="nav-link" href="/ask/">Create</a>
                </li>
                <li class="nav-item {% if request.path == "/tell/" %}active {% endif %}"">
                    <a class="nav-link" href="/tell/">Upload</a>
                </li>
                <li class="nav-item {% if request.path == "/tell/" %}active {% endif %}"">
                    <a class="nav-link" href="/tell/">Analyze</a>
                </li>
                <li class="nav-item {% if request.path == "/messages/" %}active {% endif %}"">
                    <a class="nav-link" href="/FAQ/">FAQ</a>
                </li>

            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link text-dark" href="/profile/account">{{ user.email }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="/sign-out/"><i class="fas fa-sign-out-alt"></i></a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="col-md-12 text-center">
      {% for message in messages %}
        <div class="alert {{ message.tags }}">{{ message }}</div>
      {% endfor %}
    </div>

    <div class="col-md-12">
        <div class="row text-center m-0">
          {% block content_up %}
          {% endblock content_up %}
        </div>
    </div>



    {% if user.is_authenticated %}
      {% if user.is_active %}
        {% if user.email_confirmed %}
          <div class="col-md-12">
              <div class="row text-center m-0">
                  <div class="col-md-3 " style="text-align: center;">
                      {% block content_left %}
                      {% endblock content_left %}
                  </div>
                  <div class="col-md-6 p-0" style="text-align: center;">
                     {% block content_mid %}
                     {% endblock content_mid %}
                  </div>
                  <div class="col-md-3" style="text-align: center;">
                     {% block content_right %}
                     {% endblock content_right %}
                  </div>
              </div>
              <div class="row">
                  <div class="col-md-12">
                     {% block content_bottom %}
                     {% endblock content_bottom %}
                  </div>
              </div>
          </div>
          {% else %}
            <div class="row">
              <div class="col-md-4"></div>
              <div class="col-md-4">
                <form method="post" action="/confirm_email/">
                  {% csrf_token %}
                  {{ form.non_field_errors }}
                  <div class="form-group">
                    <div class="h2 text-center">Confirmation Code</div>
                    <p class="text-center" for="id_email_code">Please enter the code sent to your email:</p>

                    <input type="email_code" class="form-control {% if form.email_code.errors %} is-invalid{% endif %}"
                           id="id_email_code" name="email_code"
                           value = "{{ form.email_code.value|default:"" }}">
                    {% if form.email_code.errors %}
                      <div class="invalid-feedback">
                        {{ form.email_code.errors }}
                      </div>
                    {% endif %}
                  </div>
              </div>
            </div>
          {% endif %}
        {% endif %}
    {% else %}
      {% if request.path == "/" %}
      <div class="row">
        <div class="col-md-2 text-center"></div>
        <div class="col-md-8 text-center">
          <div class="jumbotron" style="background:transparent !important">
            <h1 class="display-5 bg-success text-white rounded p-3">Login First!</h1>
            <p style="font-size:1.7em" class="text-info">
              <a clas href="/sign-in/">Sign In</a> | <a href="/sign-up/">Sign Up</a>
            </p>
          </div>
        </div>
      </div>
      {% else %}
        <div class="col-md-12 text-center">
          <p style="font-size:1.7em" class="text-info">
            <a clas href="/sign-in/">Sign In</a> | <a href="/sign-up/">Sign Up</a>
          </p>
        </div>
      {% endif %}

    {% endif %}

    <script src="{% static "js/popper.min.js" %}" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="{% static "js/bootstrap.min.js" %}" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script src="{% static "js/custom.js" %}"></script>
    <script src="{% static "js/jquery.ui.widget.js" %}"></script>
    <script src="{% static "js/jquery.iframe-transport.js" %}"></script>
    <script src="{% static "js/jquery.fileupload.js" %}"></script>
<!--
    <script src="{% static "js/jquery.fileupload-jquery-ui.js" %}"></script>

    <script src="{% static "js/jquery.fileupload-ui.js" %}"></script>

    <script src="{% static "js/jquery.fileupload-process.js" %}"></script>
    <script src="{% static "js/jquery.fileupload-validate.js" %}"></script>
-->

</body>
</html>

templates/home.html
{% extends 'base.html'%}
{% load static %}
{% block content_left %}
  {{ deneme }}
    <div class="row border">
        <div class="col-md-12 text-left">
            <h5>Projects</h5>
        </div>
        <div class="col-md-12 text-left">
            <button type="button" class="btn btn-sm btn-primary" data-toggle="modal" data-target="#createNewProjectModal">
                + New Project
            </button>
        </div>
        <ul>
            {% for project in projects %}
            <li class="col-md-12 text-left border p-0 mt-2 mb-2" id="project_{{ project.pk }}">
                {{ project.name }}
                <br>
                <button type="button" class="btn btn-sm btn-primary" data-toggle="modal" data-target="#addDatasetModal">
                    + Add Dataset
                </button>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock content_left %}

{% block content_mid %}

{% endblock content_mid %}

{% block content_right %}
    <div class="row">
        <div class="col-md-12 border">
            Messages
        </div>
         <ol>
            {% for message in new_messages %}
            <li class="col-md-12 text-left" id="project_{{ message.pk }}">
                {{ message.name }}
            </li>
            {% endfor %}
        </ol>
    </div>
{% endblock content_right %}

{% block content_bottom %}



  {% include "_modal_create_project.html" %}
  {% include "_modal_add_dataset.html" %}
  {% include "_modal_new_dataset.html" %}
  {% include "_modal_choose_dataset.html" %}
{% endblock content_bottom %}

templates/sign-in.html
{% extends 'base.html' %}

{% block content_up %}
  <div class="col-md-3 text-center"></div>
  <div class="col-md-6 text-center">
        <div class="jumbotron m-2 pt-3 border-left border-right border-dark rounded" style="background:transparent !important">
            <h1 class="display-3">Welcome Back!</h1>
            <p class="lead">Please enter your e-mail and password.</p>
            <div class="row">
              <div class="col-md-12">
                <form method="post">
                  {% csrf_token %}
                  {{ form.non_field_errors }}
                  <div class="form-group">
                    {{ form.email.label_tag }}
                    <input type="email" class="form-control {% if form.email.errors %} is-invalid{% endif %}"
                           id="id_email" name="email" placeholder="Enter your e-mail"
                           value = "{{ form.email.value|default:"" }}">
                    {% if form.email.errors %}
                      <div class="invalid-feedback">
                        {{ form.email.errors }}
                      </div>
                    {% endif %}
                  </div>
                  <div class="form-group">
                    {{ form.password.label_tag }}
                    <input  type="password" class="form-control {% if form.password.errors %} is-invalid{% endif %}"
                           id="id_password" name="password" value = "{{ form.password.value|default:"" }}">
                    {% if form.password.errors %}
                      <div class="invalid-feedback">
                        {{ form.password.errors }}
                      </div>
                    {% endif %}
                  </div>
                  <br>
                  <button type="submit" class="btn btn-primary btn-block">Sign in</button>
                </form>
              </div>
            </div>
        </div>
    </div>
{% endblock content_up %}

templates/sign-up.html
{% extends 'base.html' %}

{% block content_up %}
  <div class="col-md-3 text-center"></div>
  <div class="col-md-6 text-center">
        <div class="jumbotron m-2 pt-3 border-left border-right rounded border-dark" style="background:transparent !important">
            <h1 class="display-3">Start using tool!</h1>
            <p class="lead">Please fill in the form to register.</p>
            <div class="row">
              <div class="col-md-12">
                <form method="post">
                  {% csrf_token %}
                  <div class="form-group">
                    {{ form.email.label_tag }}
                    <input type="email" class="form-control {% if form.email.errors %} is-invalid{% endif %}"
                           id="id_email" name="email" placeholder="Enter your e-mail"
                           value = "{{ form.email.value|default:"" }}">
                    {% if form.email.errors %}
                      <div class="invalid-feedback">
                        {{ form.email.errors }}
                      </div>
                    {% endif %}
                  </div>
                  <div class="form-group">
                    {{ form.password1.label_tag }}
                    <input  type="password" class="form-control {% if form.password1.errors %} is-invalid{% endif %}"
                           id="id_password1" name="password1" value = "{{ form.password1.value|default:"" }}">
                    {% if form.password1.errors %}
                      <div class="invalid-feedback">
                        {{ form.password1.errors }}
                      </div>
                    {% endif %}
                  </div>
                  <div class="form-group">
                    {{ form.password2.label_tag }}
                    <input  type="password" class="form-control {% if form.password2.errors %} is-invalid{% endif %}"
                           id="id_password2" name="password2" value = "{{ form.password2.value|default:"" }}">
                    {% if form.password2.errors %}
                      <div class="invalid-feedback">
                        {{ form.password2.errors }}
                      </div>
                    {% endif %}
                  </div>
                  <br>
                  <button type="submit" class="btn btn-primary btn-block">Sign Up</button>
                </form>
              </div>
            </div>
        </div>
    </div>
{% endblock content_up %}